### PR TITLE
icons for organizations

### PR DESCRIPTION
**Pull request by borazslo**

### CODE REVIEW

**Review by martonfekete — COMMENTED** [review]
I'm wondering about the purpose of this change... What's the reason behind it? Design? "Brand" recognition?

**Comment by borazslo** [comment]
I would say "brand" recognition. One sees some logos / branding just arriving to the border. And when they check the ukrainehelp.hu they can find which organization helped them. Also when they want to find an organization somwhere in the real worls (e.g. at railway station) it is much easier to look for the logo of the organization they had contact with before.

**Comment by borazslo** [comment]
And the logos/icons/images should be much much smaller

**Comment by martonfekete** [comment]
I don't really like the way we put html in our markdown, especially with the style tag there. but I like the improvement on the end result, so let's merge and update later with a cleanup!

**Pull request merged**
